name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:

  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: mambajs

      - name: Install dependencies
        run: yarn install

      - name: Run eslint
        run: yarn run eslint:check

  unittest_and_build_wheels:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Micromamba dev env
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: mambajs

      - name: Install JS dependencies
        run: yarn install

      - name: Build mambajs JS
        run: yarn run build

      - name: Run JS tests
        run: yarn run test

      - name: Install bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Build Python wheels
        run: python scripts/build_wheels.py

      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: dist ${{ github.run_number }}
          path: ./python/dist

  test_wheel:
    runs-on: ${{ matrix.os }}-latest
    needs: [unittest_and_build_wheels]

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        include:
          - os: ubuntu
            dist: 'mambajs*linux*x86_64.whl'
          - os: windows
            dist: 'mambajs*win*.whl'
          - os: macos
            dist: 'mambajs*macos*arm64.whl'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Micromamba dev env
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: mambajs

      - uses: actions/download-artifact@v7
        with:
          name: dist ${{ github.run_number }}
          path: ./dist

      - name: Install the package
        run: pip install -vv ${{ matrix.dist }}
        working-directory: dist

      - name: Run CLI test
        run: python test_cli.py
        working-directory: tests
